language: python
python: 3.7
dist: xenial

install: "pip install tox"
script: "tox -e $TRAVIS_BUILD"

matrix:
  include:
    - env: TRAVIS_BUILD=py
      python: 3.6
    - env: TRAVIS_BUILD=py
      python: 3.5
    - env: TRAVIS_BUILD=py
    - env: TRAVIS_BUILD=lint
